### ISSUE TITLE
Error running "mix ecto.migrate" using freshly installed setup.

### ISSUE THREAD

**Issue by babakness** [AdamBrodzinski/meteor_elixir#2]
$  mix ecto.migrate

```
** (UndefinedFunctionError) undefined function: Mongo.Ecto.stop/2
    (mongodb_ecto) Mongo.Ecto.stop(#PID<0.151.0>, 5000)
    (ecto) lib/mix/ecto.ex:75: Mix.Ecto.ensure_stopped/2
    (mix) lib/mix/cli.ex:55: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

It works fine despite this however. Thanks for this project!

**Comment by AdamBrodzinski** [comment]
Hmm interesting. I haven't used the migrations for mongo (if they do anything) so perhaps the migration file isnt setup correctly. Should be ok though :smile:
